
CREATE DATABASE instagram_db;

CREATE TABLE Users(
User_Id SERIAL PRIMARY KEY ,
Username VARCHAR(50) NOT NULL,
Email VARCHAR(200) UNIQUE NOT NULL,
Full_Name VARCHAR(100) NOT NULL,
Bio TEXT,
Registration_Date TIMESTAP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Post(
Post_Id SERIAL PRIMARY KEY,
User_Id INT,
Caption TEXT,
Image_Url VARCHAR(255) NOT NULL,
Location VARCHAR(200),
Post_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Foreign KEY(User_Id)
REFERENCES  Users(User_Id)
);

CREATE TABLE comment(
comment_Id SERIAL PRIMARY KEY,
Post_Id INT ,FOREIGN KEY(Post_Id)
REFERENCES Post(Post_Id),
User_Id INT, FOREIGN KEY(User_Id)
REFERENCES Users(User_Id),
Text Varchar(255) NOT NULL,
Comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Likes(
like_Id SERIAL PRIMARY KEY,
Post_Id INT,
User_Id INT,
Like_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(Post_Id) REFERENCES Post(Post_Id),
FOREIGN KEY(User_Id) REFERENCES Users(User_Id)
);

CREATE TABLE Follower(
Folower_Id SERIAL PRIMARY KEY,
FoLLowing_User_Id INT NOT NULL,
Followers_Use
);

